name: Lint

on:
  pull_request:
    branches: [releases]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@3
        with:
          version: "0.4.20"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync --dev --extra tests

      - name: Run isort --check
        run: |
          uv run isort --check custom_components/ics_calendar tests

      - name: Run black --check
        run: |
          uv run black --check custom_components/ics_calendar tests

      - name: Run flake8
        run: |
          uv run flake8

      - name: Run pydocstyle
        run: |
          uv run pydocstyle -v custom_components/ics_calendar tests

      - name: Run pylint
        run: |
          uv run pylint custom_components/ics_calendar
